In [1]:
import sympy as sp
import numpy as np

## Problem 1

In [2]:
E, I, a, p = sp.symbols('E, I, a, p')
L = 2*a
r = 5*p*a**4/(16*E*I)

k4 = 2*E*I/L**3*sp.Matrix([[12, -6*L, -12, -6*L],
                [-6*L, 4*L**2, 6*L, 2*L**2],
                [-12, 6*L, 12, 6*L],
                [-6*L, 2*L**2, 6*L, 4*L**2]])

k3 = 3*E*I/L**3*sp.Matrix([[1, -L, -1],
                           [-L, L**2, L],
                           [-1, L, 1]])

a1 = sp.Matrix([[0], [0], [1], [0]])
a2 = sp.Matrix([[1], [0], [0]])


In [3]:
S1 = k4*a1*r
print(S1)

Matrix([[-15*a*p/16], [15*a**2*p/16], [15*a*p/16], [15*a**2*p/16]])


In [4]:
So2 = p*L/8*sp.Matrix([[-5], [L], [-3]])

S2 = k3*a2*r+So2
S2

Matrix([
[-145*a*p/128],
[17*a**2*p/64],
[-111*a*p/128]])

## Problem 2

In [18]:
alpha = np.atan2(3, 4)
print(alpha)
T_0 = np.array([[np.cos(alpha), np.sin(alpha)],
                [-np.sin(alpha), np.cos(alpha)]])
T_g = np.zeros((4,4))
T_g[0:2, 0:2] = T_0 
T_g[2:4, 2:4] = T_0
print(T_g)

v_gl = np.array([1, 0.5, 1, 0.5]).T

v_8_6 = T_g @ v_gl
print(v_8_6)

0.6435011087932844
[[ 0.8  0.6  0.   0. ]
 [-0.6  0.8  0.   0. ]
 [ 0.   0.   0.8  0.6]
 [ 0.   0.  -0.6  0.8]]
[ 1.1 -0.2  1.1 -0.2]
