In [2]:
import numpy as np

## Problem 1

### a)

In [9]:
A = np.array([[1, 6], [5, 4], [9, 2]])
B = np.array([[2, 8], [4, 3], [5, 11]])
C = np.array([[-2, 2, 5], [-2, 6, -4]])

print(A+B)
print(A-B)
print(A@C)
print(C@A)

[[ 3 14]
 [ 9  7]
 [14 13]]
[[-1 -2]
 [ 1  1]
 [ 4 -9]]
[[-14  38 -19]
 [-18  34   9]
 [-22  30  37]]
[[53  6]
 [-8  4]]


### b)

In [11]:
A = np.array([[3/5, -4/5], [4/5, 3/5]])
print(A.T)
print(np.linalg.inv(A))

[[ 0.6  0.8]
 [-0.8  0.6]]
[[ 0.6  0.8]
 [-0.8  0.6]]


### c)

In [16]:
a = np.array([[1], [2]])
alpha = 60*np.pi/180
R = np.array([[np.cos(alpha), -np.sin(alpha)], [np.sin(alpha), np.cos(alpha)]])
print(R)
print(R@a)

[[ 0.5       -0.8660254]
 [ 0.8660254  0.5      ]]
[[-1.23205081]
 [ 1.8660254 ]]


### d)

In [21]:
A = np.array([[4, 2], [3, -1]])
b = np.array([[6], [7]])
print(np.linalg.inv(A)@b)

[[ 2.]
 [-1.]]


### e)

In [22]:
A = np.array([[4, 2], [-2, -1]])
print(np.linalg.det(A))

0.0


### f)

In [25]:
A = np.array([[2, -1, 0], [1, -3, 1], [-1, 1, -3]])
b = np.array([[2], [-2], [-6]])
print(np.linalg.solve(A,b))

[[2.]
 [2.]
 [2.]]
